const bcrypt = require('bcryptjs');
const users = require('./UserRepository');
const { signToken } = require('./AuthMiddleware');
const { sendWelcomeMail } = require('../integrations/EmailService');
const { generatePassword } = require('../../shared/utils/text');

async function login(username, password) {
  const u = await users.findByUsername(username);
  if (!u || u.suspended) return { error: 'invalid' };
  const ok = await bcrypt.compare(password, u.password_hash || '');
  if (!ok) return { error: 'invalid' };
  const token = signToken(u);
  return { token, role: u.role, user: { username: u.username }, useAreas: u.use_areas, manageAreas: u.manage_areas };
}

async function changePassword(uid, currentPassword, newPassword) {
  const u = await users.findById(uid);
  if (!u) return { error: 'no-session' };
  const ok = await bcrypt.compare(currentPassword || '', u.password_hash || '');
  if (!ok) return { error: 'wrong-current' };
  const hash = await bcrypt.hash(newPassword, 10);
  await users.updatePasswordHash(u.id, hash);
  return { ok: true };
}

// Legt einen Nutzer an; generiert bei Bedarf ein Passwort und verschickt die Willkommensmail.
async function createUser(fields) {
  let password = fields.password;
  const autoGenerated = !password;
  if (autoGenerated) password = generatePassword();
  const passwordHash = await bcrypt.hash(password, 10);
  const id = await users.create({ ...fields, passwordHash });
  let mailSent = false;
  if (autoGenerated && fields.email) {
    try {
      await sendWelcomeMail(fields.email.trim(), fields.username.trim(), password, fields.first_name || '', fields.last_name || '');
      mailSent = true;
    } catch (mailErr) {
      console.error('Willkommensmail fehlgeschlagen:', mailErr.message);
    }
  }
  return { id, mailSent };
}

async function resetPassword(id, password) {
  const hash = await bcrypt.hash(password, 10);
  return users.updatePasswordHash(id, hash);
}

// Setzt ein neues Zufallspasswort und schickt die Willkommensmail erneut.
async function resendWelcome(id) {
  const u = await users.findProfileById(id);
  if (!u) return { error: 'not-found' };
  if (!u.email) return { error: 'no-email' };
  const newPassword = generatePassword();
  const hash = await bcrypt.hash(newPassword, 10);
  await users.updatePasswordHash(id, hash);
  await sendWelcomeMail(u.email, u.username, newPassword, u.first_name || '', u.last_name || '');
  return { ok: true };
}

module.exports = { login, changePassword, createUser, resetPassword, resendWelcome };
